$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
experiment_name: story-generation-training

inputs:
  story_parameters:
    type: uri_file
    path: azureml:story-params@latest

outputs:
  trained_model:
  evaluation_output:
  model_info_output_path:

settings:
  default_compute: azureml:gpu-cluster
  continue_on_step_failure: false

jobs:
  train_model:
    name: train_model
    display_name: train-story-generator
    code: ../../../data-science/src
    command: >-
      python train.py 
      --story_parameters ${{inputs.story_parameters}}
      --model_output ${{outputs.model_output}}
    environment: azureml:story-train-env@latest
    compute: azureml:gpu-cluster
    resources:
      instance_count: 1
    outputs:
      model_output: ${{parent.outputs.trained_model}}
