name: Deploy Infrastructure

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      location:
        required: true
        type: string
      namespace:
        required: true
        type: string
      postfix:
        required: true
        type: string
      enable_aml_computecluster:
        required: true
        type: boolean
      enable_monitoring:
        required: true
        type: boolean
    secrets:
      azure_creds:
        required: true
      clientId:
        required: true
      clientSecret:
        required: true
      subscriptionId:
        required: true
      tenantId:
        required: true

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure_creds }}

      - name: Create Terraform State Storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.53.0
          inlineScript: |
            # Create resource group for terraform state
            az group create \
              --name "rg-${{ inputs.namespace }}-${{ inputs.postfix }}${{ inputs.environment }}-tf" \
              --location "${{ inputs.location }}"
            
            # Create storage account for terraform state
            az storage account create \
              --name "st${{ inputs.namespace }}${{ inputs.postfix }}${{ inputs.environment }}tf" \
              --resource-group "rg-${{ inputs.namespace }}-${{ inputs.postfix }}${{ inputs.environment }}-tf" \
              --location "${{ inputs.location }}" \
              --sku "Standard_LRS" \
              --kind "StorageV2"
            
            # Create container for terraform state
            az storage container create \
              --name "default" \
              --account-name "st${{ inputs.namespace }}${{ inputs.postfix }}${{ inputs.environment }}tf"
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.7
          
      - name: Terraform Init
        run: |
          cd infrastructure
          terraform init \
            -backend-config="resource_group_name=rg-${{ inputs.namespace }}-${{ inputs.postfix }}${{ inputs.environment }}-tf" \
            -backend-config="storage_account_name=st${{ inputs.namespace }}${{ inputs.postfix }}${{ inputs.environment }}tf" \
            -backend-config="container_name=default" \
            -backend-config="key=mlops-tab"
            
      - name: Terraform Plan
        run: |
          cd infrastructure
          terraform plan \
            -var="location=${{ inputs.location }}" \
            -var="namespace=${{ inputs.namespace }}" \
            -var="postfix=${{ inputs.postfix }}" \
            -var="environment=${{ inputs.environment }}" \
            -var="enable_aml_computecluster=${{ inputs.enable_aml_computecluster }}" \
            -var="enable_monitoring=${{ inputs.enable_monitoring }}"
            
      - name: Terraform Apply
        run: |
          cd infrastructure
          terraform apply -auto-approve \
            -var="location=${{ inputs.location }}" \
            -var="namespace=${{ inputs.namespace }}" \
            -var="postfix=${{ inputs.postfix }}" \
            -var="environment=${{ inputs.environment }}" \
            -var="enable_aml_computecluster=${{ inputs.enable_aml_computecluster }}" \
            -var="enable_monitoring=${{ inputs.enable_monitoring }}"

